title: Matthew Cassidy
author: Matthew Cassidy
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Matthew Cassidy is a software developer. This site will focus
  on his experience, values, and principles.

# social links
github_username:  cassidmj # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
